added check servername function

diff --git a/dynip_update b/dynip_update
--- a/dynip_update
+++ b/dynip_update
@@ -4,13 +4,13 @@
 # Scripts that updates dynamic DNS servers using HTTPS via CURL.
 # Curl is a required package. Please make sure it's installed!
 # Currently supports Internet.bs and NO-IP.com providers.
-# Custom parameters are set in /etc/dynip_update.conf - PLESE UPDATE
-# THAT FILE - DO NOT CHANGE THIS SCRIPT.
+# Custom parameters are set in /etc/dynip_update.conf
+# PLEASE UPDATE THAT FILE - DO NOT CHANGE THIS SCRIPT.
 ####################################################################
 ####################################################################
 
-# Version 3.1
-# Serial 202000181558
+# Version 3.2
+# Serial 202004181751
 
 # Include custom parameters for this script
 CONFIG_FILE='/etc/dynip_update.conf'
@@ -20,8 +20,11 @@ source ${CONFIG_FILE}
 # get deleted in case of reboot).
 ME=`basename $0`
 FILESPATH="/root"
-P_IP="${FILESPATH}/${ME}_p_ip.txt"
 
+P_IP="${FILESPATH}/${ME}_p_ip.txt"
+SERVERNAME_CHECKFILE="${FILESPATH}/${ME}_servername.chk"
+    
+FORCE_UPDATE='false'
 ####################################################################
 
 DYNHOSTNAME="${SERVERNAME}.${DOMAINNAME}"
@@ -36,7 +39,6 @@ case ${DYNIPPROV} in
 		UPDATETYPE=1
 		;;
 	cloudflare)
-    CF_IDS_FILE="$FILESPATH/${ME}_cloudflare.ids"
 		UPDATETYPE=2
 		;;
 	*)
@@ -45,41 +47,59 @@ case ${DYNIPPROV} in
 		;;
 esac
 
+
 get_ip () {
-# curl randomly one of the services and check that the output is actually an IP
-# store this into CURR_IP variable and increment TRIES counter variable
-declare -a SERVICES=($GET_IP_SERVERS)
-SRV=${SERVICES[$((  RANDOM % ${#SERVICES[@]}  ))]}
-CURR_IP="`${CURL} -s --retry 3 --retry-delay 5 -m 15 ${SRV} | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'`"
-(( TRIES++ ))
+  # curl randomly one of the services and check that the output is actually an IP
+  # store this into CURR_IP variable and increment TRIES counter variable
+  declare -a SERVICES=($GET_IP_SERVERS)
+  SRV=${SERVICES[$((  RANDOM % ${#SERVICES[@]}  ))]}
+  CURR_IP="`${CURL} -s --retry 3 --retry-delay 5 -m 15 ${SRV} | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'`"
+  (( TRIES++ ))
 }
 
 check_ip () {
-# Check if CURR_IP is empty and retry for a number of times stored into MAXTRIES
-if [ -z "${CURR_IP}" ]
-  then retry ${MAXTRIES}
-fi
+  # Check if CURR_IP is empty and retry for a number of times stored into MAXTRIES
+  if [ -z "${CURR_IP}" ]
+    then retry ${MAXTRIES}
+  fi
 }
 
 retry () {
-# If you've reached already MAXTRIES, notify. 
-# Otherwise retry to get the IP, log it, increase the counter and check_ip again
-if [ ${TRIES} -eq $1 ]
-  then 
-	notify "Unable to get current IP for `hostname` - ${DYNHOSTNAME} after $1 attempts reached -> Aborting" ; exit 1
-  else
-	get_ip
-	# Just log the retries (no notifications)
-	logger "${BASH_SOURCE[0]} PID $$ is retrying to get the IP using ${SRV}: attempt #${TRIES}"
-	check_ip
-fi
+  # If you've reached already MAXTRIES, notify. 
+  # Otherwise retry to get the IP, log it, increase the counter and check_ip again
+  if [ ${TRIES} -eq $1 ]
+    then 
+    notify "Unable to get current IP for `hostname` - ${DYNHOSTNAME} after $1 attempts reached -> Aborting" ; exit 1
+    else
+    get_ip
+    # Just log the retries (no notifications)
+    logger "${BASH_SOURCE[0]} PID $$ is retrying to get the IP using ${SRV}: attempt #${TRIES}"
+    check_ip
+  fi
+}
+
+check_if_servername_has_changed () {
+  touch ${SERVERNAME_CHECKFILE}
+  # Make sure the SERVERNAME hasn't changed. If so, 
+  # 1) reset the AUTO_RECORD_IDENTIFIER in the CONF_FILE
+  # 2) reset the AUTO_RECORD_IDENTIFIER runtime var
+  # 3) update the SERVERNAME_CHECKFILE with the SERVERNAME
+  # 4) set FORCE_UPDATE to 'true'
+  PREVIOUS_SERVER_NAME="$(cat ${SERVERNAME_CHECKFILE})"
+  if [ "${PREVIOUS_SERVER_NAME}" != "${SERVERNAME}" ]; then
+    sed -i "s/^AUTO_RECORD_IDENTIFIER=.*$/AUTO_RECORD_IDENTIFIER=/g" ${CONFIG_FILE}
+    AUTO_RECORD_IDENTIFIER=''
+    echo "${SERVERNAME}" > ${SERVERNAME_CHECKFILE}
+    FORCE_UPDATE='true'
+  fi
+
 }
 
 is_update_required () {
-# In case of IP mismatch between current and previous, update and notify
+# If FORCE_UPDATE is 'true' or in case of IP mismatch between current and previous IP
+# update and notify
 PREV_IP=`cat $P_IP`
-if [ "${CURR_IP}" != "${PREV_IP}" ] 
-   then 
+if ${FORCE_UPDATE} || [ "${CURR_IP}" != "${PREV_IP}" ]; then
 	store_ip
 	update_ip ${UPDATETYPE}
 	notify "New IP ${CURR_IP} set for ${DYNHOSTNAME} - at `date "+%H:%M %d/%m/%Y"` from `hostname`"
@@ -124,21 +144,23 @@ if [[ `echo "${RESULT}" | grep -c "good"` -ne 1 ]]
 fi
 }
 
+
 update_ip_type2 () {
-if [ -z ${AUTO_RECORD_IDENTIFIER} ]; then
+
+  # If the DNS record Identifier is not set, get it via API and update the CONFIG_FILE
+  if [ -z ${AUTO_RECORD_IDENTIFIER} ]; then
     AUTO_RECORD_IDENTIFIER="$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/${ZONEID}/dns_records?name=${DYNHOSTNAME}" -H "Authorization: Bearer ${TOKEN}" -H "Content-Type: application/json"  | grep -Po '(?<="id":")[^"]*')"
     echo "${DYNHOSTNAME} DNS record identifier is ${AUTO_RECORD_IDENTIFIER}. Updating ${CONFIG_FILE}"
     sed -i "s/^AUTO_RECORD_IDENTIFIER=.*$/AUTO_RECORD_IDENTIFIER='${AUTO_RECORD_IDENTIFIER}'/g" ${CONFIG_FILE}
-fi
+  fi
 
-update=$(curl -s -X PUT "https://api.cloudflare.com/client/v4/zones/${ZONEID}/dns_records/${AUTO_RECORD_IDENTIFIER}" -H "Authorization: Bearer ${TOKEN}" -H "Content-Type: application/json" --data "{\"id\":\"${ZONEID}\",\"type\":\"A\",\"name\":\"${DYNHOSTNAME}\",\"content\":\"${CURR_IP}\",\"ttl\":${TTL}}")
+  update=$(curl -s -X PUT "https://api.cloudflare.com/client/v4/zones/${ZONEID}/dns_records/${AUTO_RECORD_IDENTIFIER}" -H "Authorization: Bearer ${TOKEN}" -H "Content-Type: application/json" --data "{\"id\":\"${ZONEID}\",\"type\":\"A\",\"name\":\"${DYNHOSTNAME}\",\"content\":\"${CURR_IP}\",\"ttl\":${TTL}}")
 
-if [[ $update == *"\"success\":false"* ]]; then
-    message="API UPDATE FAILED. DUMPING RESULTS:\n$update"
-    notify "$message"
-    exit 1
-fi
-
+  if [[ $update == *"\"success\":false"* ]]; then
+      message="API UPDATE FAILED. DUMPING RESULTS:\n$update"
+      notify "$message"
+      exit 1
+  fi
 }
 
 store_ip () {
@@ -155,5 +177,6 @@ MAXTRIES=3
 
 get_ip
 check_ip
+check_if_servername_has_changed
 is_update_required
 
